### ISSUE TITLE
Package URL is invalid

### ISSUE THREAD

**Issue by alexmurray** [pspiagicw/emacs#1]
The URL specified in the theme file is not valid:

https://github.com/pspiagicw/emacs/blob/c5e268c9f9c5ed4523be28a8fcab921e8c108751/catppuccin-theme.el#L11

Instead this should be: `https://github.com/pspiagicw/emacs`

**Comment by pspiagicw** [comment]
The repository will be transferred to `github.com/catppuccin` , so the URL was planned to be `github.com/catppuccin/emacs` which it would be after the transfer. Thanks for noticing the error!
